### ISSUE TITLE
Issue with breaking blocks in a chunk (Unloaded chunk at x, y, z)

### ISSUE THREAD

**Issue by Fisher2911** [hollow-cube/minestom-ce#59]
Basically, I'm trying to create an instance for a player in the PlayerLoginEvent, but it seems like when the player breaks a block, it throws an error in console and doesn't drop an item. This same code was working with regular Minestom.

[Player login listener](https://paste.helpch.at/atijederel.kotlin)
[CustomChunkGenerator](https://paste.helpch.at/ujaqiduyos.kotlin)
[Block I'm trying to break that doesn't drop anything](https://paste.helpch.at/gekiyuradu.kotlin)
[createDefaultHandler method](https://paste.helpch.at/quyasinuje.kotlin) - this is where the error occurs
Version: 
```gradle
implementation("dev.hollowcube:minestom-ce:010fe985bb")
```
Error:
```
java.lang.NullPointerException: Unloaded chunk at -144,-64,112
	at net.minestom.server.instance.Instance.getBlock(Instance.java:596)
	at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:218)
	at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:226)
	at io.github.fisher2911.myserver.world.BlockHandlersKt$createDefaultHandler$3.onDestroy(BlockHandlers.kt:32)
	at net.minestom.server.instance.DynamicChunk.setBlock(DynamicChunk.java:111)
	at net.minestom.server.instance.Chunk.setBlock(Chunk.java:91)
	at net.minestom.server.instance.AnvilLoader.loadBlockEntities(AnvilLoader.java:300)
	at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:129)
	at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:87)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$6(InstanceContainer.java:294)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Fisher2911** [comment]
It only seems to be happening when loading chunks from a file

**Comment by Fisher2911** [comment]
The issue seems to be that the chunk is cached _after_ the chunk is generated

**Comment by Fisher2911** [comment]
If you want to reproduce, this causes it:
```kotlin
MinecraftServer.getBlockManager().registerHandler("minecraft:stone") {
    object : BlockHandler {
        override fun getNamespaceId(): NamespaceID {
            return NamespaceID.from("minecraft:stone")
        }
        override fun onDestroy(destroy: BlockHandler.Destroy) {
            println("destroyed stone")
            val position = destroy.blockPosition
            destroy.instance.getBlock(position)
        }
    }
}

instanceContainer.chunkLoader = AnvilLoader("worlds/${player.uuid}")
instanceContainer.setGenerator { unit: GenerationUnit -> unit.modifier().fillHeight(0, 40, Block.STONE)

private fun onPlayerLogout(
    globalEventHandler: GlobalEventHandler,
    barrenInstanceManager: BarrenInstanceManager,
    playerManager: PlayerManager
) {
    globalEventHandler.addListener(
        PlayerDisconnectEvent::class.java
    ) { event: PlayerDisconnectEvent ->
        val player: Player = event.player
        player.instance.saveChunksToStorage()
    }
}
```
Steps:
1. Join the server
2. Leave
3. Join back
